### ISSUE TITLE
Usable with AWS Cloud Search?

### ISSUE THREAD

**Issue by helpermethod** [jcustenborder/kafka-connect-solr#37]
We think about migrating from Solr to AWS CloudSearch and wonder if the connector would also be usable with CloudSearch (or could be made usable)?

**Comment by jcustenborder** [comment]
Hi @helpermethod

I personally haven't tried it. I don't know if it would work. I'm leaning towards it not working because it looks like they have a custom api on top of solr.

**Comment by helpermethod** [comment]
Thanks, I may fork your connector and see if I can somehow make it compatible with CloudSearch.
