### ISSUE TITLE
Maven shade plugin

### ISSUE THREAD

**Issue by evolv34** [jcustenborder/kafka-connect-solr#6]
Hi Jeremy,

I have updated pom.xml with maven shade plugin. Could you please take a look at the PR ? 

https://github.com/jcustenborder/kafka-connect-solr/pull/5

Thank you.

**Comment by jcustenborder** [comment]
@evolv34 Maven shade isn't a good idea with connectors. This is also controlled in a parent pom. Use on the the installation packages.
